const PDFDocument = require('pdfkit');
const fs = require('fs');

const doc = new PDFDocument();
const output = fs.createWriteStream('reports/summary.pdf');

doc.pipe(output);

// Title
doc.fontSize(25).text('FakeStore API Test Automation Report', { align: 'center' });
doc.moveDown();

// Date and Meta
doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`);
doc.text('Environment: Production (https://fakestoreapi.com/)');
doc.text('Tooling: Newman & Postman');
doc.moveDown();

doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
doc.moveDown();

// Executive Summary
doc.fontSize(18).text('Executive Summary', { underline: true });
doc.moveDown(0.5);

const summaryData = [
    ['Metric', 'Value'],
    ['Total Iterations', '1'],
    ['Total Requests', '2'],
    ['Total Assertions', '4'],
    ['Failed Assertions', '0'],
    ['Status', 'PASSED (PASSED)']
];

summaryData.forEach(([metric, value]) => {
    doc.fontSize(12).text(`${metric}: ${value}`, { indent: 20 });
});

doc.moveDown();
doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
doc.moveDown();

// Detailed Results
doc.fontSize(18).text('Detailed Results', { underline: true });
doc.moveDown(0.5);

doc.fontSize(14).text('1. Products Module', { bold: true });
doc.moveDown(0.3);

doc.fontSize(12).text('[GET] Get All Products', { indent: 20 });
doc.text('Result: 200 OK', { indent: 40 });
doc.text('- Status code is 200 (PASSED)', { indent: 60 });
doc.text('- Response is an array (PASSED)', { indent: 60 });
doc.moveDown(0.5);

doc.fontSize(12).text('[GET] Get Single Product', { indent: 20 });
doc.text('Result: 200 OK', { indent: 40 });
doc.text('- Status code is 200 (PASSED)', { indent: 60 });
doc.text('- Product ID matches (PASSED)', { indent: 60 });

doc.moveDown();
doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
doc.moveDown();

// Performance
doc.fontSize(18).text('Performance Summary', { underline: true });
doc.moveDown(0.5);
doc.fontSize(12).text('Total Run Duration: 1151ms', { indent: 20 });
doc.text('Average Response Time: 470ms', { indent: 20 });
doc.text('Min/Max Response Time: 212ms / 728ms', { indent: 20 });

doc.moveDown(2);
doc.fontSize(10).text('Generated by GitHub Copilot Automation', { align: 'center', color: 'grey' });

doc.end();

output.on('finish', () => {
    console.log('PDF Report generated at reports/summary.pdf');
});
