const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const doc = new PDFDocument();
const output = fs.createWriteStream('reports/summary.pdf');

doc.pipe(output);

// Title
doc.fontSize(25).text('FakeStore API Test Automation Report', { align: 'center' });
doc.moveDown();

// Date and Meta
doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`);
doc.text('Environment: Production (https://fakestoreapi.com/)');
doc.text('Generated by: GitHub Copilot Automation');
doc.moveDown();

doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
doc.moveDown();

// 1. Functional Testing Summary (Newman)
const newmanReportPath = 'reports/report.json';
if (fs.existsSync(newmanReportPath)) {
    try {
        const newmanData = JSON.parse(fs.readFileSync(newmanReportPath, 'utf8'));
        const stats = newmanData.run.stats;
        const failures = newmanData.run.failures;

        doc.fontSize(18).text('Functional Testing Summary (Postman/Newman)', { underline: true });
        doc.moveDown(0.5);

        const functionalSummary = [
            ['Total Requests', stats.requests.total],
            ['Failed Requests', stats.requests.failed],
            ['Total Assertions', stats.assertions.total],
            ['Failed Assertions', stats.assertions.failed],
            ['Status', stats.assertions.failed === 0 ? 'PASSED' : 'FAILED']
        ];

        functionalSummary.forEach(([metric, value]) => {
            doc.fontSize(12).text(`${metric}: ${value}`, { indent: 20 });
        });

        if (failures && failures.length > 0) {
            doc.moveDown(0.5);
            doc.fontSize(14).text('Failures:', { bold: true, indent: 20 });
            failures.forEach((failure, index) => {
                doc.fontSize(10).text(`${index + 1}. ${failure.error.name}: ${failure.error.message}`, { indent: 40, color: 'red' });
            });
            doc.fillColor('black');
        }

        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
    } catch (err) {
        console.error('Error parsing Newman report:', err);
    }
}

// 2. Performance Testing Summary (k6)
const k6ReportPath = 'reports/performance-summary.json';
if (fs.existsSync(k6ReportPath)) {
    try {
        const k6Data = JSON.parse(fs.readFileSync(k6ReportPath, 'utf8'));
        const metrics = k6Data.metrics;

        doc.fontSize(18).text('Performance Testing Summary (k6)', { underline: true });
        doc.moveDown(0.5);

        const httpReqDuration = metrics.http_req_duration.values;
        const httpReqFailed = metrics.http_req_failed.values;
        const iterations = metrics.iterations.values;

        const perfSummary = [
            ['Total Iterations', iterations.count],
            ['Total Requests', metrics.http_reqs.values.count],
            ['Avg Response Time', `${httpReqDuration.avg.toFixed(2)}ms`],
            ['P95 Response Time', `${httpReqDuration['p(95)'].toFixed(2)}ms`],
            ['Min Response Time', `${httpReqDuration.min.toFixed(2)}ms`],
            ['Max Response Time', `${httpReqDuration.max.toFixed(2)}ms`],
            ['Failure Rate', `${(httpReqFailed.rate * 100).toFixed(2)}%`],
            ['Status', k6Data.root_group.checks.every(c => c.passes > 0 && c.fails === 0) ? 'PASSED' : 'CHECK REQUISITES']
        ];

        perfSummary.forEach(([metric, value]) => {
            doc.fontSize(12).text(`${metric}: ${value}`, { indent: 20 });
        });

        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
    } catch (err) {
        console.error('Error parsing k6 report:', err);
    }
}

doc.moveDown(2);
doc.fontSize(10).text('End of Report', { align: 'center', color: 'grey' });

doc.end();

output.on('finish', () => {
    console.log('PDF Report generated at reports/summary.pdf');
});
